---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache validity in seconds
  become: yes

- name: Install necessary packages for kernel compilation
  apt:
    name:
      - build-essential
      - gcc
      - make
      - bc
      - libncurses-dev
      - bison
      - flex
      - libssl-dev
      - libelf-dev
      - gawk
      - openssl
      - dkms
      - libudev-dev
      - libpci-dev
      - libiberty-dev
      - autoconf
      - git
      - liblz4-tool
    state: latest
  become: yes

- name: Generate locale
  command: locale-gen en_US.UTF-8
  become: yes

- name: Set system locale
  become: yes
  copy:
    content: |
      LANG=en_US.UTF-8
      LANGUAGE=en_US.UTF-8
      LC_ALL=en_US.UTF-8
    dest: /etc/default/locale
    owner: root
    group: root
    mode: '0644'

- name: Set shell environment variables
  become: yes
  lineinfile:
    path: /etc/profile.d/locale.sh
    create: yes
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8

- name: Clone Linux kernel source
  git:
    repo: "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
    dest: "{{ clone_destination }}/linux"
    clone: yes
    update: yes
