---
- name: Update all packages
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache validity in seconds
  become: yes

- name: Install necessary packages for kernel compilation
  apt:
    name:
      - build-essential
      - gcc
      - make
      - git
      - rt-tests
    state: latest
  become: yes

- name: Clone schbench repository
  git:
    repo: git://git.kernel.org/pub/scm/linux/kernel/git/mason/schbench.git
    dest: "{{ clone_destination }}/schbench"
    version: master

- name: Build schbench
  make:
    chdir: "{{ clone_destination }}/schbench"

- name: Create a symbolic link for hackbench
  file:
    src: "{{ clone_destination }}/schbench/schbench"
    dest: "{{ bin_location }}/schbench"
    state: link
